### ISSUE TITLE
Improved Support for Immersive Engineering Outfitter Villagers

### ISSUE THREAD

**Issue by MuteTiefling** [Mrbysco/JustEnoughProfessions#1]
## SUGGESTIONS
- [ ] I would like to propose new content.
- [x] I would like to propose changes.
- [ ] I would like to propose another thing.

## SUGGESTION INFORMATION

Currently JEI shows that any banner will work as a POI for Outfitter villagers, but this isn't quite accurate. It instead needs to be a banner that has been right clicked with any Shader from IE.

I'd propose making an exception here to add some explanatory text since I don't think there's a good way for you you display this nuance visually.

**Comment by Mrbysco** [comment]
![image](https://user-images.githubusercontent.com/9308260/107414272-11f84a00-6b12-11eb-8ec8-02e5b6d839cb.png)
Is that enough explanatory text?

**Comment by MuteTiefling** [comment]
Yep, I think that's good. Thanks :D

**Comment by Mrbysco** [comment]
Will be available next version which I will upload ASAP when further testing is done

**Comment by MuteTiefling** [comment]
Awesome, much appreciated ^_^

**Comment by Mrbysco** [comment]
It's been uploaded to Curse. So now it's up to them to approve :)

**Comment by Mrbysco** [comment]
https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep/files/3198370

**Comment by superblast1** [comment]
hey in the current version this no longer seems to be a thing 1.20.1

![Image](https://github.com/user-attachments/assets/22503b22-a000-46bb-b0c2-07edd845805f)
