### ISSUE TITLE
[Suggestion]: Change Server side support on modrinth from required to unsupported

### ISSUE THREAD

**Issue by Einhornyordle** [Mrbysco/JustEnoughProfessions#14]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

JEI is marked as unsupported on server side while JEP ist marked as required on modrinth. When installing a modpack from modrinth as a server instance (in a launchers which support this like the AT Launcher), they will not download JEI (since it is unsuported) while still downloading JEP (since it is required), causing it to crash the server since on startup due to the missing dependency.

**Comment by Mrbysco** [comment]
That goes against their description on modrinth where it says some features will be disabled if ran client-only on a server

**Comment by Mrbysco** [comment]
Which to me indicate that server-side is at most optional but not unsupported

**Comment by Einhornyordle** [comment]
So it's JEI who's wrong with stating that it is unsupported server-side when it actually works fine?

**Comment by Mrbysco** [comment]
At best it's optional on servers. It should be able to be installed on server-side just fine

**Comment by Einhornyordle** [comment]
I see, thank you
