### ISSUE TITLE
[Suggestion]: Would it be possible to port to EMI?

### ISSUE THREAD

**Issue by Kevin-Marsh** [Mrbysco/JustEnoughProfessions#16]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

EMI is becoming more used in 1.21 due to some developers dropping support for JEI and adding native compatibility for EMI to their mods. While adding JEI and EMI is a potential solution to get compatibility it potentially introduces some lag and potential issues. A native EMI port would allow packs like ATM10 who are trying to only use EMI to support your mod.

**Comment by Mrbysco** [comment]
The question for me is. Would showing Worktables on EMI even be viable? Isn't EMI build for calculating costs of recipes? And workstations aren't really a recipe

**Comment by Kevin-Marsh** [comment]
EMI is a direct replacement for JEI. It has the additional ability to calculate recipes but it is an item display mod the same as JEI. Here is Apothic Spawners in EMI for instance. It has the same capabilities as JEI to create  custom recipe categories where the mod ports in compatibility.
![2024-07-18_07 55 11](https://github.com/user-attachments/assets/ec58b267-aba2-4ec5-97a5-e8ec14a7cb5f)

**Comment by Mrbysco** [comment]
I'll look into it

**Comment by Mrbysco** [comment]
![image](https://github.com/user-attachments/assets/97820530-b777-429a-bc27-ec5405e10857)

**Comment by Mrbysco** [comment]
Done. See https://github.com/Mrbysco/EMIProfessions

**Comment by Kevin-Marsh** [comment]
Thank you so much for that.

**Comment by Mrbysco** [comment]
It's now available https://www.curseforge.com/minecraft/mc-mods/emi-professions-emip
