### ISSUE TITLE
[Suggestion]: Remove JEI as a dep so I can use Roughly Enough Items

### ISSUE THREAD

**Issue by aaronhowser1** [Mrbysco/JustEnoughProfessions#3]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

REI supposedly works out of the box with everything that uses JEI, but JEP has JEI as a dependency so the game doesn't launch without it.

**Comment by Mrbysco** [comment]
You can still use REI, you just have to remove the JEI and install the REI workaround mod. 
![image](https://user-images.githubusercontent.com/9308260/142874598-6cf5b2c2-9a9a-4ec8-a75f-34635023b3c1.png)

Tested and works just fine
