### ISSUE TITLE
[Suggestion]: Compatibility with Domestication Innovation 

### ISSUE THREAD

**Issue by katubug** [Mrbysco/JustEnoughProfessions#8]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Hi! I'm running MC 1.18.2 with Forge 40.1.84, and version 1.2.2 of Just Enough Professions. I am using a mod called Domestication Innovation, which adds an Animal Tamer, whose job block is a Pet Bed. This does not appear in my list of professions, although all vanilla and several modded vendors show correctly. It would be awesome if the mod was natively compatible with this mod, or if there was a way for me to add compatibility through CraftTweaker or something. Thank you!

**Comment by Mrbysco** [comment]
Found the issue and will push a new build out soon
