### ISSUE TITLE
[Suggestion]: Catalyst tag

### ISSUE THREAD

**Issue by kyragit** [Mrbysco/JustEnoughProfessions#9]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I'm making a pack with totally custom villager trades that don't use emeralds, but you can only see JEP by clicking U on an emerald (or villager spawn egg). It would be really nice if there was a tag for these, so I could add my own catalysts.

**Comment by Mrbysco** [comment]
I don't think JEI allows tags as catalyst

**Comment by Mrbysco** [comment]
Last time I checked JEI doesn't allow you to use tags as catalysts
